var first_name = document.createElement('input');
first_name.setAttribute('type', 'text');
first_name.setAttribute('id', 'first_name');
first_name.setAttribute('placeholder', 'First Name');
document.body.appendChild(first_name);
var last_name = document.createElement('input');
last_name.setAttribute('type', 'text');
last_name.setAttribute('id', 'last_name');
last_name.setAttribute('placeholder', 'Last Name');
document.body.appendChild(last_name);
var address = document.createElement('input');
address.setAttribute('type', 'text');
address.setAttribute('id', 'address');
address.setAttribute('placeholder', 'Address');
document.body.appendChild(address);
var submit = document.createElement('button');
submit.setAttribute('type', 'button');
submit.setAttribute('id', 'submit');
submit.innerHTML = 'Submit';
document.body.appendChild(submit);
var table = document.createElement('table');
table.setAttribute('id', 'table');
document.body.appendChild(table);
var row = document.createElement('tr');
row.setAttribute('id', 'row');
document.getElementById('table').appendChild(row);
var first_name_header = document.createElement('th');
first_name_header.innerHTML = 'First Name';
document.getElementById('row').appendChild(first_name_header);
var last_name_header = document.createElement('th');
last_name_header.innerHTML = 'Last Name';
document.getElementById('row').appendChild(last_name_header);
var address_header = document.createElement('th');
address_header.innerHTML = 'Address';
document.getElementById('row').appendChild(address_header);
var index = 0;
document.getElementById('submit').onclick = function() {
  var first_name_value = document.getElementById('first_name').value;
  var last_name_value = document.getElementById('last_name').value;
  var address_value = document.getElementById('address').value;
  var row = document.createElement('tr');
  row.setAttribute('id', 'row' + index);
  document.getElementById('table').appendChild(row);
  var first_name_data = document.createElement('td');
  first_name_data.innerHTML = first_name_value;
  document.getElementById('row' + index).appendChild(first_name_data);
  var last_name_data = document.createElement('td');
  last_name_data.innerHTML = last_name_value;
  document.getElementById('row' + index).appendChild(last_name_data);
  var address_data = document.createElement('td');
  address_data.innerHTML = address_value;
  document.getElementById('row' + index).appendChild(address_data);
  index++;
};
