var full_name = document.createElement('input');
full_name.setAttribute('type', 'text');
full_name.setAttribute('id', 'full_name');
full_name.setAttribute('placeholder', 'Full Name');
document.body.appendChild(full_name);
var email = document.createElement('input');
email.setAttribute('type', 'text');
email.setAttribute('id', 'email');
email.setAttribute('placeholder', 'Email');
document.body.appendChild(email);
var phone = document.createElement('input');
phone.setAttribute('type', 'text');
phone.setAttribute('id', 'phone');
phone.setAttribute('placeholder', 'Phone');
document.body.appendChild(phone);
var submit = document.createElement('button');
submit.setAttribute('type', 'button');
submit.setAttribute('id', 'submit');
submit.innerHTML = 'Submit';
document.body.appendChild(submit);
